// This file has been autogenerated.

exports.scopes = [[function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '6eb11d2ab13349fdabe7d42bb84d5a3b',
  date: 'Fri, 03 May 2013 18:31:30 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .put('/xplat1?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 03 May 2013 18:31:31 GMT',
  etag: '"0x8D01643911272D9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0cea121e-a144-4b4e-b520-6ec67a88470f',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:30 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '63793d4e187f4cf1b4beda83440ee41c',
  date: 'Fri, 03 May 2013 18:31:32 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .delete('/xplat1?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '54d8acbd-ebaa-4cf0-b2be-672fd7a15f9b',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:32 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '0187c78a6db14309a148919c6a2540d4',
  date: 'Fri, 03 May 2013 18:31:36 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .put('/xplat2?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 03 May 2013 18:31:37 GMT',
  etag: '"0x8D0164394C94CDF"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1da95b31-fe94-4f49-b667-6798cafed7d7',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:36 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '218cb395bbe64f92b7b89521112f6e60',
  date: 'Fri, 03 May 2013 18:31:39 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .get('/?comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults AccountName=\"https://ciserversdk.blob.core.windows.net/\"><Containers><Container><Name>mycontainer</Name><Url>https://ciserversdk.blob.core.windows.net/mycontainer</Url><Properties><Last-Modified>Fri, 03 May 2013 14:51:49 GMT</Last-Modified><Etag>\"0x8D01624E002FBD4\"</Etag></Properties></Container><Container><Name>xplat2</Name><Url>https://ciserversdk.blob.core.windows.net/xplat2</Url><Properties><Last-Modified>Fri, 03 May 2013 18:31:37 GMT</Last-Modified><Etag>\"0x8D0164394C94CDF\"</Etag></Properties></Container></Containers><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'dff32bc6-21c0-46cf-8aec-dc7c0ebc2dd1',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:40 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': 'a9e9412c47de4263bcef4b49d9eed546',
  date: 'Fri, 03 May 2013 18:31:42 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .delete('/xplat2?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd0be3259-26bc-4086-bec6-c3f960a9b872',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:43 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': 'bb0a506ea5794de58f0f5c1d6f684936',
  date: 'Fri, 03 May 2013 18:31:45 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .put('/xplat3?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 03 May 2013 18:31:46 GMT',
  etag: '"0x8D016439A18B82A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '8fd5341a-6ce8-445d-99ac-c47895e09874',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:45 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '501dafe3729a49cb993057526d9dc2c5',
  date: 'Fri, 03 May 2013 18:31:49 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .head('/xplat3?restype=container&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 03 May 2013 18:31:46 GMT',
  etag: '"0x8D016439A18B82A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'daa989cd-79e8-473a-931c-043e2d3678a7',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:50 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .get('/xplat3?restype=container&comp=acl')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><SignedIdentifiers />", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  'last-modified': 'Fri, 03 May 2013 18:31:46 GMT',
  etag: '"0x8D016439A18B82A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ae5b9dcf-7e4a-407e-8d25-2db8cbd28d0d',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:51 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': 'bdcd08b307df43a8a79131a0e5237ee6',
  date: 'Fri, 03 May 2013 18:31:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .delete('/xplat3?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '644edd7b-96c8-458a-9ac3-ffc21086e178',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:54 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '265051d6b3764f24ac858206e1f6d381',
  date: 'Fri, 03 May 2013 18:31:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .put('/xplat4?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 03 May 2013 18:31:57 GMT',
  etag: '"0x8D01643A0EAB8AE"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a4d6f2b8-a4e5-4e6c-bd56-0734f136f376',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:31:57 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': 'acbb98e2f5be4430abdb945cb14d6fbe',
  date: 'Fri, 03 May 2013 18:32:00 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/xplat4/blob3', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'XUFAKrxLKna5cZ2REBfFkg==',
  'last-modified': 'Fri, 03 May 2013 18:32:01 GMT',
  etag: '"0x8D01643A33E7A01"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '639bd1ca-cf3b-4fb0-b8be-ad2fb489d1aa',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:01 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': 'c1388429d7144fdfbbed4ac7a2ab51ab',
  date: 'Fri, 03 May 2013 18:32:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .delete('/xplat4?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b753e442-18a4-4ed0-bd61-8f06925dba97',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:04 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '57ee31bf81b44b7da4f441084b345685',
  date: 'Fri, 03 May 2013 18:32:07 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .put('/xplat5?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 03 May 2013 18:32:07 GMT',
  etag: '"0x8D01643A6E5B4DB"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3f26395d-6b84-4b00-83d1-65e79b67820c',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:07 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '5ede3dd1e0b84e3284a33d5c8fa2423d',
  date: 'Fri, 03 May 2013 18:32:09 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .put('/xplat6?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 03 May 2013 18:32:11 GMT',
  etag: '"0x8D01643A8D44B0C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b3eec634-8aea-4b75-8387-d519431c2565',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:10 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': 'b802b60dfe184b378919ca9c9ac2a4dc',
  date: 'Fri, 03 May 2013 18:32:14 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/xplat6/blob5', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': '/F4DjTilcDIIVEHn/nAQsA==',
  'last-modified': 'Fri, 03 May 2013 18:32:15 GMT',
  etag: '"0x8D01643AB4BF061"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '594c7764-6ff2-49da-ad15-0ed9ec563676',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:14 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '6447b00c28ad4a0fbfa2d98901f5f765',
  date: 'Fri, 03 May 2013 18:32:17 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .get('/xplat6?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ContainerName=\"https://ciserversdk.blob.core.windows.net/xplat6\"><Blobs><Blob><Name>blob5</Name><Url>https://ciserversdk.blob.core.windows.net/xplat6/blob5</Url><Properties><Last-Modified>Fri, 03 May 2013 18:32:15 GMT</Last-Modified><Etag>0x8D01643AB4BF061</Etag><Content-Length>10</Content-Length><Content-Type>text/plain;charset=\"utf-8\"</Content-Type><Content-Encoding /><Content-Language /><Content-MD5 /><Cache-Control /><BlobType>BlockBlob</BlobType><LeaseStatus>unlocked</LeaseStatus></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fc3425fd-d65a-4875-9db3-e165a6967d87',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:20 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '718c068e22544a4aa7651670ce6d9557',
  date: 'Fri, 03 May 2013 18:32:24 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .delete('/xplat6?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ce9ddb91-85a9-4a51-bb57-8cf952e76b26',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:24 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '7038ddd1458d461d8b67ce638857dd57',
  date: 'Fri, 03 May 2013 18:32:27 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .delete('/xplat5?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '066760b0-8d52-4b5b-81ec-9d7c691e87cc',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:28 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '55ca2eda6db44f0b963eddaad302dcc5',
  date: 'Fri, 03 May 2013 18:32:31 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .put('/xplat7?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 03 May 2013 18:32:32 GMT',
  etag: '"0x8D01643B5C1D48D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5a96d650-6748-4cb6-879b-3d9fb94bcf77',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:32 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '111260f718934c1f9dc762deebfe8a2d',
  date: 'Fri, 03 May 2013 18:32:34 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .put('/xplat8?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 03 May 2013 18:32:36 GMT',
  etag: '"0x8D01643B80BB7D3"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ab94e156-0acb-43d7-a9da-744c021eb377',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:36 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': 'a3bf11a7c58141b692afc6adb437460c',
  date: 'Fri, 03 May 2013 18:32:38 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/xplat8/blob7', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': '/F4DjTilcDIIVEHn/nAQsA==',
  'last-modified': 'Fri, 03 May 2013 18:32:39 GMT',
  etag: '"0x8D01643B9E8EFB1"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '603c893e-a764-4f65-96d1-59084712b695',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:39 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': 'c108487d0ac5431b88afdc62a5bfad32',
  date: 'Fri, 03 May 2013 18:32:41 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .get('/xplat8/blob7')
  .reply(200, "helloworld", { 'content-length': '10',
  'content-type': 'text/plain;charset="utf-8"',
  'last-modified': 'Fri, 03 May 2013 18:32:39 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D01643B9E8EFB1"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '8e282888-2480-4ddb-b483-168e2a5dff09',
  'x-ms-version': '2011-08-18',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'BlockBlob',
  date: 'Fri, 03 May 2013 18:32:42 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '3740c6436e474f6dae0275136d167a47',
  date: 'Fri, 03 May 2013 18:32:44 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .delete('/xplat8?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6a11bd00-b698-4673-a666-1762e6c6219d',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:44 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.core.windows.net:443')
  .get('/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk/keys')
  .reply(200, "<StorageService xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Url>https://management.core.windows.net/db1ab6f0-4769-4b27-930e-01e2ef9c123c/services/storageservices/ciserversdk</Url><StorageServiceKeys><Primary>Cgs+V9zd4hJBLnziS9DG24FAJ9RO5nITnACQ0VanQnxQfG3cZCCm01BRxlGd/RBvXdrqwIXEyMUOz+/+kgbalA==</Primary><Secondary>j3CPPVExgiK79KQbn+fwSkFegHBs4DRYyKYjrJxZv4Owrg7y/X0sGEk7rp07c6WRGvqfc3mhSQMjUBjbGw60JQ==</Secondary></StorageServiceKeys></StorageService>", { 'cache-control': 'no-cache',
  'content-length': '514',
  'content-type': 'application/xml; charset=utf-8',
  server: '33.0.6198.30 (rd_rdfe_stable.130419-2156) Microsoft-HTTPAPI/2.0',
  'x-ms-servedbyregion': 'ussouth',
  'x-ms-request-id': '5ef776b26e734c9eaca492042aa368d2',
  date: 'Fri, 03 May 2013 18:32:48 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://ciserversdk.blob.core.windows.net:443')
  .delete('/xplat7?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '8da97349-f8be-4919-813d-7c050d0e2b14',
  'x-ms-version': '2011-08-18',
  date: 'Fri, 03 May 2013 18:32:48 GMT' });
 return result; }]];